x=int(input("x:"))
y=int(input("y:"))
x1=int(input("x1:"))
y1=int(input("y1:"))
x2=int(input("x2:"))
y2=int(input("y2:"))
A=(x1<x<x2 and y2<y<y1)
print("Вершина (x1,y1):({0},{1})".format(x1,y1))
print("Вершина (x2,y2):({0},{1})".format(x2,y2))
print("Точка (x,y):({0},{1})".format(x,y))
print("Точка лежит внутри прямоугольника? ",A)